[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "python311Packages.pypdf2"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "npm start"
